### ISSUE TITLE
crypto error

### ISSUE THREAD

**Issue by c0mputerking** [EstebanMonge/kanboard_imap_tasks#4]
I get the below error when i try to run the plugin command manually or as cron.

Also is this plugin updated to work with the new 1.40 version as i think some new functionality regarding email  is included.

/var/www/html/plugins/Imap/cron.php /var/www/html/data/db.sqlite
PHP Warning:  fopen(): Peer certificate CN=`localhost' did not match expected CN=`list.changed.for.this.report' in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/J
sonRPC/HttpClient.php on line 269
PHP Warning:  fopen(): Failed to enable crypto in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 269
PHP Warning:  fopen(https://list.changed.for.this.report:2574): failed to open stream: operation failed in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/H
ttpClient.php on line 269
PHP Fatal error:  Uncaught JsonRPC\Exception\ConnectionFailureException: Unable to establish a connection in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonR
PC/HttpClient.php:272
Stack trace:
#0 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(193): JsonRPC\HttpClient->execute('{"jsonrpc":"2.0...')
#1 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(178): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...')
#2 /var/www/html/plugins/Imap/cron.php(59): JsonRPC\Client->execute('getAllProjects')
#3 {main}
  thrown in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 272
root@list:~#

**Comment by EstebanMonge** [comment]
Are you using a self signed https certificate?

**Comment by c0mputerking** [comment]
Yes

Sent from Nine
________________________________

**Comment by EstebanMonge** [comment]
I only tested without https, if you are using the script in the same server that have installed Kanboard, you can use http, can you try without https?

**Comment by c0mputerking** [comment]
Ok just for full disclosure I have attached a screenshot of my imap integration settings NOTE i changed to from https://mydomain.com:2547 to http://localhost after the screen shot and now i get the error below not quite sure what to put here i also tried http://mydomain.com:2547 but that did not work either. 
/var/www/html/plugins/Imap/cron.php /var/www/html/data/db.sqlite PHP Warning:  fopen( http://localhost ): failed to open stream: Connection refused in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 269 PHP Fatal error:  Uncaught JsonRPC\Exception\ConnectionFailureException: Unable to establish a connection in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonR PC/HttpClient.php:272 Stack trace: #0 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(193): JsonRPC\HttpClient->execute('{"jsonrpc":"2.0...') #1 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(178): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...') #2 /var/www/html/plugins/Imap/cron.php(59): JsonRPC\Client->execute('getAllProjects') #3 {main} thrown in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 272 


Application URL or Localhost Application URL 
http://localhost 





PS thank you for your help so far 


I only tested without https, if you are using the script in the same server that have installed Kanboard, you can use http, can you try without https?

**Comment by c0mputerking** [comment]
Still not exactly sure what i am doing here, but i got http://localhost working, I tested it with lynx and it takes me to the KanBoard login page. A have also entered http://localhost into the Integration Imap section inside Application URL or Localhost Application URL. Now i get a different error so i guess that is some progress :) but still not working 

# /var/www/html/plugins/Imap/cron.php /var/www/html/data/db.sqlite 

PHP Fatal error:  Uncaught JsonRPC\Exception\InvalidJsonFormatException: Malformed payload in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Validator/Js onFormatValidator.php:26 Stack trace: #0 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Response/ResponseParser.php(86): JsonRPC\Validator\JsonFormatValidator :: validate(NULL) #1 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(194): JsonRPC\Response\ResponseParser->parse() #2 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(178): JsonRPC\Client->sendPayload('{"jsonrpc":"2.0...') #3 /var/www/html/plugins/Imap/cron.php(59): JsonRPC\Client->execute('getAllProjects') #4 {main} thrown in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Validator/JsonFormatValidator.php on line 26 

Computer King CaN-Mail Surveillance King 
http://computerking.ca http://canmail.org http://surveillanceking.net 

Surveillance - Sales Service - Hosting Backup 
Internet Based Surveillance Systems 
Custom Service Pac kages 
Secure IMAP Email - Automated Remote Backups - Photo Blogs - Online ERP and Accounting Packages 

----- Original Message -----

**Comment by EstebanMonge** [comment]
I used this:
http://localhost/kanboard/jsonrpc.php

**Comment by EstebanMonge** [comment]
Did works?

**Comment by c0mputerking** [comment]
Nope I tried adding http://localhost/kanboard/jsonrpc.php 
and still not still not working 

/var/www/html/plugins/Imap/cron.php /var/www/html/data/db.sqlite PHP Fatal error:  Uncaught JsonRPC\Exception\ConnectionFailureException: Response: HTTP/1.1 40 4 Not Found in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php: 386 Stack trace: #0 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php(285): JsonRP C\HttpClient->handleExceptions(Array) #1 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(193): JsonRPC\Ht tpClient->execute('{"jsonrpc":"2.0...') #2 /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/Client.php(178): JsonRPC\Cl ient->sendPayload('{"jsonrpc":"2.0...') #3 /var/www/html/plugins/Imap/cron.php(59): JsonRPC\Client->execute('getAllProjects') #4 {main} thrown in /var/www/html/plugins/Imap/vendor/fguillot/json-rpc/src/JsonRPC/HttpClient.php on line 386 

Computer King CaN-Mail Surveillance King 
http://computerking.ca http://canmail.org http://surveillanceking.net 

Surveillance - Sales Service - Hosting Backup 
Internet Based Surveillance Systems 
Custom Service Pac kages 
Secure IMAP Email - Automated Remote Backups - Photo Blogs - Online ERP and Accounting Packages 

----- Original Message -----

**Comment by EstebanMonge** [comment]
Have you get working this plugin?

**Comment by c0mputerking** [comment]
No cannot get it working yet 

Computer King CaN-Mail Surveillance King 
http://computerking.ca http://canmail.org http://surveillanceking.net 

Surveillance - Sales Service - Hosting Backup 
Internet Based Surveillance Systems 
Custom Service Pac kages 
Secure IMAP Email - Automated Remote Backups - Photo Blogs - Online ERP and Accounting Packages 

----- Original Message -----

**Comment by c0mputerking** [comment]
Has there been any progress on this plugin yet? as i still cannot get IMAP working
